-- Jalankan di Supabase SQL Editor
-- Tabel komentar film/series

CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  media_type text NOT NULL DEFAULT 'movie',
  tmdb_id bigint NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Index untuk query cepat per film
CREATE INDEX IF NOT EXISTS idx_comments_media
  ON public.comments (media_type, tmdb_id, created_at DESC);

-- RLS: siapa saja bisa baca, cuma pemilik yang bisa hapus/ubah
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "comments_read_all" ON public.comments
  FOR SELECT USING (true);

CREATE POLICY "comments_insert_own" ON public.comments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "comments_delete_own" ON public.comments
  FOR DELETE USING (auth.uid() = user_id);